### PR TITLE
Update version to 2.8.2

### PR DESCRIPTION
**Pull request by ytrrty**

### CODE REVIEW

**Comment by ytrrty** [comment]
@adelgado Hi, could you please merge this update?

**Comment by adelgado** [comment]
Hello @ytrrty, thanks for the PR.

I would actually prefer to only package the unminified versions of the library. Could you update this PR?

**Comment by ytrrty** [comment]
@adelgado Yep, updated

**Comment by ytrrty** [comment]
@adelgado Will you merge this PR?

**Pull request merged**
